version: "3.3"

services:
  db:
    image: mysql:5.7
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zsk
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app

  php:
    # image: php:apache
    build: ./app
    links:
      - db
    volumes:
      - ./app:/app/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: zsk
      DB_USER: user
      DB_PASSWORD: password

volumes:
  mysql-data: {}
