version: "3.3"

services:
  db:
    image: postgres:11.11-alpine
    volumes:
      - data:/var/lib/postgresql
      # - ./db.sh:/docker-entrypoint-initdb.d/init.sh
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ts-password
      SCHEMA: admin
      ANON: web_anon
      AUTHENTICATOR: authenticator

  # pgadmin:
  #   image: dpage/pgadmin4:5.1
  #   depends_on:
  #     - db
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #     PGADMIN_LISTEN_PORT: 80
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "8081:80"

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app

  php:
    # image: php:apache
    build: ./app
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./app:/app/app
    environment:
      DATABASE_URL: postgres://user:password@db:5432/zsk
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: admin
      DB_USER: admin
      DB_PASSWORD: ts-password

volumes:
  data: {}
  pgadmin: {}
