[[redirects]]
  from = "/app/*"
  to = "https://tadeushare-backend.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/g/*"
  to = "https://tadeushare-backend.herokuapp.com/get/:splat"
  status = 200

[[redirects]]
  from = "/r/*"
  to = "https://tadeushare-backend.herokuapp.com/raw/:splat"
  status = 200
